apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-application-back
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates a NEG after an Ingress is created
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-application-back
  template:
    metadata:
      labels:
        app: todo-application-back
    spec:
      volumes:
        - name: shared-todo-application
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: todo-application-back
          image: gcr.io/PROJECT_ID/IMAGE
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-db-secret
                key: DATABASE_PASSWORD
          volumeMounts:
          - name: shared-todo-application
            mountPath: /usr/src/app/files
          resources:
            limits:
              cpu: 29m
              memory: 100Mi

              