apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-application-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-application-back
  template:
    metadata:
      labels:
        app: todo-application-back
    spec:
      containers:
        - name: todo-application-back
          image: gcr.io/PROJECT_ID/IMAGE
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-db-secret
                key: DATABASE_PASSWORD