apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/service.yaml
- backend/rollout.yaml
- backend/service.yaml
- backend/horizontalpodautoscaler.yaml
- ingress.yaml
- analysistemplate.yaml
images:
- name: PROJECT/BACKEND
  newName: muhakka/dwk-4-gitops-project-back
  newTag: latest
- name: PROJECT/FRONTEND
  newName: muhakka/dwk-4-gitops-project-front
  newTag: latest