apiVersion: v1
kind: Service
metadata:
  namespace: devops-with-kubernetes-project
  name: todo-application-back-svc
spec:
  type: NodePort
  selector:
    app: todo-application
  ports:
    - port: 2346
      protocol: TCP
      nodePort: 30080
      targetPort: 5050