apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
  namespace: devops-with-kubernetes-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: PROJECT/BROADCASTER
          env:
            - name: NATS_URL
              value: nats://my-nats:4222
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram-bot-token
                  key: TOKEN