apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops-with-kubernetes
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: muhakka/logoutput-vol-http:latest
          env:
            # Define the environment variable
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
                  name: example-configmap
                  # Specify the key associated with the value
                  key: example.message
          resources:
            limits:
              cpu: 100m
              memory: 500Mi