apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-application-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-application-front
  template:
    metadata:
      labels:
        app: todo-application-front
    spec:
      containers:
        - name: todo-application-front
          image: gcr.io/PROJECT_ID/IMAGE
          resources:
            requests:
              cpu: 50m
              memory: 190Mi
            limits:
              cpu: 50m
              memory: 190Mi