apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-application-front
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates a NEG after an Ingress is created
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-application-front
  template:
    metadata:
      labels:
        app: todo-application-front
    spec:
      containers:
        - name: todo-application-front
          image: gcr.io/PROJECT_ID/IMAGE_FRONT
          resources:
            limits:
              cpu: 28m
              memory: 100Mi
          readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      