apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-application-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-application-front
  template:
    metadata:
      labels:
        app: todo-application-front
    spec:
      containers:
        - name: todo-application-front
          image: gcr.io/PROJECT_ID/IMAGE
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 140Mi
            limits:
              cpu: 10m
              memory: 140Mi
      