apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-application-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-application-front
  template:
    metadata:
      labels:
        app: todo-application-front
    spec:
      containers:
        - name: todo-application-front
          image: gcr.io/PROJECT_ID/IMAGE
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 20m
              memory: 200Mi
            limits:
              cpu: 20m
              memory: 200Mi
      