apiVersion: v1
kind: Service
metadata:
  name: todo-application-front-svc
spec:
  type: NodePort
  selector:
    app: todo-application-front
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080