apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend/service.yaml
- backend/service.yaml
- broadcaster/deployment.yaml
- broadcaster/secret.enc.yaml
- daily-todo-cronjob/daily-todo-cronjob.yaml
- postgres/postgres.yaml
- postgres/secret.enc.yaml
- ingress.yaml
- deployment.yaml
- analysistemplate.yaml
- rollout.yaml
images:
- name: PROJECT/BACKEND
  newName: muhakka/dwk-4-gitops-project-back
  newTag: latest
- name: PROJECT/FRONTEND
  newName: muhakka/dwk-4-gitops-project-front
  newTag: latest
- name: PROJECT/BROADCASTER
  newName: muhakka/dwk-4-gitops-project-broadcaster
  newTag: latest
- name: PROJECT/DAILY-CRONJOB
  newName: muhakka/dwk-4-gitops-project-cronjob
  newTag: latest