apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops-with-kubernetes-project
  name: todo-application-dep
spec:
  replicas: 4
  selector:
    matchLabels:
      app: todo-application
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-application
    spec:
      containers:
        - name: todo-application-back
          image: PROJECT/BACKEND
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-secret
                  key: DATABASE_PASSWORD
            - name: NATS_URL
              value: nats://my-nats:4222
          readinessProbe:
            initialDelaySeconds: 30 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
              path: /healthz
              port: 5050
          livenessProbe:
            initialDelaySeconds: 30 # Initial delay until the liveness is tested
            periodSeconds: 5 # How often to test
            httpGet:
              path: /healthz
              port: 5050
        - name: todo-application-front
          image: PROJECT/FRONTEND
          readinessProbe:
            initialDelaySeconds: 30 # Initial delay until the readiness is tested
            periodSeconds: 5 # How often to test
            httpGet:
              path: /healthz
              port: 8080
          livenessProbe:
            initialDelaySeconds: 30 # Initial delay until the liveness is tested
            periodSeconds: 5 # How often to test
            httpGet:
              path: /healthz
              port: 8080