apiVersion: v1
kind: Service
metadata:
  name: todo-application-front-svc
spec:
  type: NodePort
  selector:
    app: todo-application
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 8080