apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpushredder-hpa-back
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-application-back
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpushredder-hpa-front
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-application-front
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50