apiVersion: v1
kind: Service
metadata:
  namespace: devops-with-kubernetes
  name: pingpong-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3001