apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: devops-with-kubernetes
  name: pingpong-dep
spec:
  template:
    metadata:
      name: pingpong-dep-serverless
    spec:
      containers:
        - name: pingpong
          image: muhakka/pingpong-vol-http:latest
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-db-secret
                key: DATABASE_PASSWORD