name: Delete branch environment
on:
  delete: 

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH: "${{ github.event.ref }}"
jobs:
  build-publish-deploy:
    name: Deleting the branch environment
    runs-on: ubuntu-latest

    steps:

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

      - name: Delete environment
        run: |-
          echo "$BRANCH"
          kubectl delete namespace "$BRANCH"
