name: Release application frontend
on:
  push: 
    paths:
      - 'part3/3.2/app2-toDo/frontend/**'
      - '.github/workflows/project_front.yml'
      
env:
  PROJECT_FRONT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGE: todo-application-front
jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - run: gcloud --quiet auth configure-docker

      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

      - name: Build
        run: |-
          docker build --tag "gcr.io/$PROJECT_FRONT_ID/$IMAGE:latest" part3/3.2/app2-toDo/frontend/
  
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_FRONT_ID/$IMAGE:latest"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Deploy
        run: |-
          cd ./part3/3.2/app2-toDo/frontend/
          kustomize edit set image gcr.io/PROJECT_FRONT_ID/IMAGE=gcr.io/$PROJECT_FRONT_ID/$IMAGE:latest
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment todo-application-front
          kubectl get services -o wide